version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 9080:80
      - 443:443
    volumes:
      - /srv/nginx/html:/usr/share/nginx/html
      - /srv/nginx/conf.d:/etc/nginx/conf.d
      - /srv/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/nginx/log:/var/log/nginx
      - /srv/letsencrypt/:/etc/letsencrypt/
    environment:
      - TZ=Asia/Shanghai
    links:
      - nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - mariadb
      - redis
    links:
      - mariadb
    ports:
      - 9081:80/tcp
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Aisa/Shanghai
      - DB_HOST=mariadb
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=nextcloud
      - REDIS_HOST=redis
    volumes:
       - /srv/nextcloud:/var/www/html  

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /srv/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    environment:
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
    volumes:
      - /srv/onlyoffice/data:/var/www/onlyoffice/Data
      - /srv/onlyoffice/logs:/var/log/onlyoffice
    restart: always
    ports:
      - 9082:80
    links:
      - mariadb

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    volumes:
      - /srv/bitwarden:/data
    ports:
      - "9083:80"
      - "9084:3012"
    environment:
      SIGNUPS_ALLOWED: 'true'